### PR TITLE
Implement Ultra High Availability (HA) Support Using Patroni and etcd.

### PR DESCRIPTION
**Pull request by ibrarahmad**
This commit introduces support for Ultra High Availability (HA) using Patroni
and etcd. Changes include modifications to service scripts for Patroni and
etcd, the addition of Python scripts patroni.py and etcd.py for installation and
management, and removing the deprecated patron-cluster.py script. Ultra HA
functionality is now integrated into the pgedge cluster command to enhance
the reliability and resilience of pgEdge.

### CODE REVIEW

**Comment by luss** [comment]
This mostly looks excellent 2 me.    I don't understand why `patroni` and `etcd` are on the `fire-list`.   Lets meet w Cady, resolve how we are using, and get this kewl new stuff checked in.

**Comment by ibrarahmad** [comment]
This is because we want to control the etcd and patroni from pgedge cli. It
makes it independent of path of etcd and patroni installation and path. The
cluster command only issue pgedge cli to configuration etcd and patroni

Ibrar Ahmed

**Comment by ibrarahmad** [comment]
I have removed the "etcd" and "patroni" from the fire list.

**Comment by luss** [comment]
looks good brother.   I'm closing this pull request with checking it in though...   The new default development branch is REL24_Q3 and if you submit this pull request there I will squash merge iut right aaway

**Pull request closed without merging**
